# Simple workflow for deploying static content to GitHub Pages
name: deploy static page

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - run: cp checkswipe.js website/checkswipe.js
      - run: cp checkswipe.css website/checkswipe.css
      - run: curl 'https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.classless.min.css' -o website/pico.classless.min.css
      - run: curl 'https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png' -o website/buymeacoffee.png
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './website'
      - uses: actions/deploy-pages@v4
        name: deploy
        id: deployment
